/*
 * This program will ask user to input the number of monitors they own
 * Aswell as mice
 * 
 */
package watercosumtion.java;

import java.util.Scanner;

/**
 *
 * @author Jordan Hamilton
 */
public class WaterCosumtionJava {

 public static void main(Script[] args) {

    Scanner Keyedinput = new Scanner(System.in);
    System.out.println("Enter Number of Monitors");
    Keyedinput.nextInt();
  } 
}

